import { test, expect } from '@playwright/test'

async function loginMaster(page: any) {
  await page.goto('login')
  await page.evaluate(() => { localStorage.clear(); sessionStorage.clear() })
  await page.fill('input[placeholder="email"]', 'master.teste@pbta.dev')
  await page.fill('input[placeholder="senha"]', 'Test1234!')
  await page.getByRole('button', { name: 'Entrar com Email' }).click()
}

test('Criar movimento, ativar/desativar e refletir em ficha e sessão', async ({ page }) => {
  await loginMaster(page)
  await page.getByRole('link', { name: 'Nova Campanha' }).click()
  await page.getByRole('heading', { name: 'Nova Campanha' }).waitFor()
  await page.getByPlaceholder('Ex: A Sombra do Dragão').fill('Campanha Moves')
  await page.getByPlaceholder('Descreva o cenário inicial...').fill('Fluxo de Moves')
  await page.getByRole('button', { name: 'Criar Campanha' }).click()
  await page.goto('dashboard/master')
  await page.waitForFunction(() => document.querySelectorAll('.campaign-card').length >= 1)
  await page.locator('.campaign-card').first().click()
  const url = page.url()
  const campaignId = url.split('/').pop() || ''

  await page.goto(`/campaigns/${campaignId}/moves`)
  await page.getByText('Movimentos').waitFor()
  await page.getByLabel('Nome').fill('Ataque Preciso')
  await page.getByLabel('Descrição').fill('Ataque com precisão')
  await page.getByLabel('Modificador').selectOption('2')
  await page.getByLabel('Ativo').check()
  await page.getByRole('button', { name: 'Criar' }).click()
  await expect(page.getByText('created')).toBeVisible()
  await expect(page.locator('input[value="Ataque Preciso"]')).toBeVisible()

  await page.goto(`/characters/${campaignId}`)
  await page.getByText('Minha Ficha').waitFor()
  await page.getByLabel('Nome').fill('Jogador Moves')
  await page.getByLabel('Antecedentes').fill('Tester')
  await page.getByRole('group', { name: 'Força' }).getByLabel('1', { exact: true }).click()
  await page.getByRole('group', { name: 'Agilidade' }).getByLabel('1', { exact: true }).click()
  await page.getByRole('group', { name: 'Sabedoria' }).getByLabel('1', { exact: true }).click()
  await page.getByText('Ataque Preciso').click()
  await page.getByRole('button', { name: 'Criar Ficha' }).click()
  await expect(page.getByText('created')).toBeVisible()

  await page.goto(`/campaigns/${campaignId}/sessions`)
  await page.getByText('Criar Sessão').waitFor()
  await page.getByLabel('Nome').fill('Sessão Moves')
  const d = new Date()
  const ds = `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`
  await page.getByLabel('Data').fill(ds)
  await page.getByRole('button', { name: 'Criar' }).click()
  await page.getByRole('link', { name: 'Abrir' }).click()
  await page.getByLabel('Quem').selectOption({ label: 'Jogador: Jogador Moves' })
  await page.getByLabel('Movimento').selectOption({ label: 'Ataque Preciso' })

  await page.goto(`/campaigns/${campaignId}/moves`)
  const nameInput = page.locator('input[value="Ataque Preciso"]')
  const row = nameInput.locator('..').locator('..').locator('..')
  await row.getByLabel('Ativo').uncheck()
  await row.getByRole('button', { name: 'Salvar' }).click()
  await expect(page.getByText('saved')).toBeVisible()
  const firstLink = page.locator('.list-item').first().locator('a', { hasText: 'Abrir' })
  const href = await firstLink.getAttribute('href')
  const sessionId = (href || '').split('/').pop() || ''
  await page.goto(href || `/sessions/${sessionId}`)
  await page.getByText('Rolagens PBtA').waitFor()
  await page.getByLabel('Quem').selectOption({ label: 'Jogador: Jogador Moves' })
  const opts = await page.getByLabel('Movimento').locator('option').allTextContents()
  expect(opts.includes('Ataque Preciso')).toBe(false)
})
