import { test, expect } from '@playwright/test'

async function loginMaster(page: any) {
  await page.goto('login')
  await page.evaluate(() => { localStorage.clear(); sessionStorage.clear() })
  await page.fill('input[placeholder="email"]', 'master.teste@pbta.dev')
  await page.fill('input[placeholder="senha"]', 'Test1234!')
  await page.getByRole('button', { name: 'Entrar com Email' }).click()
  await page.goto('dashboard/master')
  await expect(page.getByPlaceholder('Nome')).toBeVisible({ timeout: 15000 })
}

test('NPCs: bloqueia soma inválida e cria com soma válida', async ({ page }) => {
  await loginMaster(page)
  await page.getByPlaceholder('Nome').fill('Campanha NPCs')
  await page.getByPlaceholder('Plot (opcional)').fill('Fluxo de NPCs')
  page.once('dialog', d => d.accept())
  await page.getByRole('button', { name: 'Criar' }).click()
  await page.waitForTimeout(500)
  await page.goto('dashboard/master')
  await page.locator('.campaign-card', { hasText: 'Campanha NPCs' }).first().click()
  await page.waitForURL(/\/campaigns\/[^/]+$/)
  await page.getByRole('button', { name: 'Fichas' }).click()
  await page.getByRole('heading', { name: 'Fichas de NPC/PDM' }).waitFor()
  await expect(page.getByText('Nenhum NPC criado.')).toBeVisible()
  await page.getByRole('button', { name: 'Novo NPC' }).click()
  await page.getByLabel('Nome do NPC').fill('NPC Inválido')
  await page.getByLabel('Background').fill('Teste')
  await page.getByLabel('Força').fill('2')
  await page.getByLabel('Agilidade').fill('2')
  await page.getByLabel('Sabedoria').fill('-1')
  await page.getByLabel('Carisma').fill('0')
  await page.getByLabel('Intuição').fill('0')
  await expect(page.getByRole('button', { name: 'Criar NPC' })).toBeDisabled()
  await page.getByLabel('Nome do NPC').fill('NPC Válido')
  await page.getByLabel('Força').fill('1')
  await page.getByLabel('Agilidade').fill('1')
  await page.getByLabel('Sabedoria').fill('1')
  await page.getByLabel('Carisma').fill('0')
  await page.getByLabel('Intuição').fill('0')
  await page.getByRole('button', { name: 'Criar NPC' }).click()
  await expect(page.getByText('NPC criado com sucesso!')).toBeVisible()
  await expect(page.getByText('NPC Válido')).toBeVisible()
})

test('NPCs: criação em lote e edição', async ({ page }) => {
  await loginMaster(page)
  await page.getByPlaceholder('Nome').fill('Campanha NPCs Lote')
  await page.getByPlaceholder('Plot (opcional)').fill('Teste de criação em lote')
  page.once('dialog', d => d.accept())
  await page.getByRole('button', { name: 'Criar' }).click()
  await page.waitForTimeout(500)
  await page.goto('dashboard/master')
  await page.locator('.campaign-card', { hasText: 'Campanha NPCs Lote' }).first().click()
  await page.waitForURL(/\/campaigns\/[^/]+$/)
  await page.getByRole('button', { name: 'Fichas' }).click()
  await page.getByRole('button', { name: 'Criar em Lote' }).click()
  const npcsData = [
    { nome: 'Aldeão Comum', antecedentes: 'Aldeão simples', forca: 1, agilidade: 1, sabedoria: 1, carisma: 0, intuicao: 0 },
    { nome: 'Guarda da Cidade', antecedentes: 'Protetor da cidade', forca: 2, agilidade: 0, sabedoria: 1, carisma: 0, intuicao: 0 },
    { nome: 'Comerciante', antecedentes: 'Negociante experiente', forca: 0, agilidade: 1, sabedoria: 2, carisma: 0, intuicao: 0 }
  ]
  for (const npc of npcsData) {
    await page.getByLabel('Nome do NPC').fill(npc.nome)
    await page.getByLabel('Background').fill(npc.antecedentes)
    await page.getByLabel('Força').fill(String(npc.forca))
    await page.getByLabel('Agilidade').fill(String(npc.agilidade))
    await page.getByLabel('Sabedoria').fill(String(npc.sabedoria))
    await page.getByLabel('Carisma').fill(String(npc.carisma))
    await page.getByLabel('Intuição').fill(String(npc.intuicao))
    await page.getByRole('button', { name: 'Adicionar ao Lote' }).click()
  }
  await page.getByRole('button', { name: 'Criar 3 NPC(s)' }).click()
  await expect(page.getByText('3 NPC(s) criado(s) com sucesso!')).toBeVisible()
  for (const npc of npcsData) {
    await expect(page.getByText(npc.nome)).toBeVisible()
  }
  await page.getByRole('button', { name: 'Editar' }).first().click()
  await page.getByLabel('Nome do NPC').fill('Aldeão Modificado')
  await page.getByRole('button', { name: 'Criar NPC' }).click()
  await expect(page.getByText('NPC atualizado com sucesso!')).toBeVisible()
  await page.waitForURL(/\/campaigns\/[^/]+$/)
  await expect(page.getByText('Aldeão Modificado')).toBeVisible()
})

test('NPCs: exclusão de NPCs', async ({ page }) => {
  await loginMaster(page)
  await page.getByPlaceholder('Nome').fill('Campanha NPCs Exclusão')
  await page.getByPlaceholder('Plot (opcional)').fill('Teste de exclusão')
  page.once('dialog', d => d.accept())
  await page.getByRole('button', { name: 'Criar' }).click()
  await page.waitForTimeout(500)
  await page.goto('dashboard/master')
  await page.locator('.campaign-card', { hasText: 'Campanha NPCs Exclusão' }).first().click()
  await page.waitForURL(/\/campaigns\/[^/]+$/)
  await page.getByRole('button', { name: 'Fichas' }).click()
  await page.getByRole('button', { name: 'Novo NPC' }).click()
  await page.getByLabel('Nome do NPC').fill('NPC para Excluir')
  await page.getByLabel('Background').fill('Teste de exclusão')
  await page.getByLabel('Força').fill('1')
  await page.getByLabel('Agilidade').fill('1')
  await page.getByLabel('Sabedoria').fill('1')
  await page.getByLabel('Carisma').fill('0')
  await page.getByLabel('Intuição').fill('0')
  await page.getByRole('button', { name: 'Criar NPC' }).click()
  await expect(page.getByText('NPC criado com sucesso!')).toBeVisible()
  await expect(page.getByText('NPC para Excluir')).toBeVisible()
  const item = page.locator('li', { hasText: 'NPC para Excluir' })
  page.once('dialog', d => d.accept())
  await item.getByRole('button', { name: 'Excluir' }).click()
  await expect(page.getByText('NPC excluído com sucesso!')).toBeVisible()
  await expect(page.getByText('NPC para Excluir')).not.toBeVisible()
})
