import { test, expect } from '@playwright/test'

async function setupSessionWithRoll(page: any) {
  await page.goto('login')
  await page.evaluate(() => { localStorage.clear(); sessionStorage.clear() })
  await page.fill('input[placeholder="email"]', 'master.teste@pbta.dev')
  await page.fill('input[placeholder="senha"]', 'Test1234!')
  await page.getByRole('button', { name: 'Entrar com Email' }).click()
  await page.getByPlaceholder('Nome').fill('Campanha Del')
  await page.getByPlaceholder('Plot (opcional)').fill('Teste')
  await page.getByRole('button', { name: 'Criar' }).click()
  await page.goto('dashboard/master')
  const idText = await page.locator('li >> nth=-1').locator('span').nth(1).textContent()
  const campaignId = (idText || '').replace('#','').trim()
  await page.goto(`/campaigns/${campaignId}`)
  await page.getByRole('button', { name: 'Fichas' }).click()
  const npcCard = page.locator('.card').filter({ hasText: 'Criar NPCs' })
  await npcCard.getByPlaceholder('Nome').fill('Orc')
  await npcCard.getByPlaceholder('Antecedentes').fill('NPC')
  const selects = npcCard.locator('select')
  await selects.nth(0).selectOption('1')
  await selects.nth(1).selectOption('1')
  await selects.nth(2).selectOption('1')
  await npcCard.getByRole('button', { name: 'Adicionar à lista' }).click()
  await npcCard.getByRole('button', { name: 'Criar NPCs' }).click()
  await page.goto(`/campaigns/${campaignId}/sessions`)
  await page.getByLabel('Nome').fill('Sessão X')
  const d = new Date(); const ds = `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`
  await page.getByLabel('Data').fill(ds)
  await page.getByRole('button', { name: 'Criar' }).click()
  const firstLink = page.locator('.list-item').first().locator('a', { hasText: 'Abrir' })
  const href = await firstLink.getAttribute('href')
  await page.goto(href!)
  await page.waitForLoadState('networkidle')
  await page.getByText('Rolagens PBtA').waitFor()
  await page.getByLabel('Quem').selectOption({ label: 'NPC: Orc' })
  await page.getByRole('button', { name: 'Rolar' }).click()
  const currentUrl = page.url()
  return currentUrl
}

test('Mestre consegue excluir rolagem e jogador não vê botão', async ({ page, browser }) => {
  const sessionUrl = await setupSessionWithRoll(page)
  await expect(page.getByText(/Histórico/)).toBeVisible()
  const before = await page.locator('text=Dados:').count()
  await page.getByRole('button', { name: 'Deletar' }).click()
  const after = await page.locator('text=Dados:').count()
  expect(after).toBe(before - 1)
  const playerContext = await browser.newContext()
  const playerPage = await playerContext.newPage()
  await playerPage.goto('login')
  await playerPage.fill('input[placeholder="email"]', 'player.teste@pbta.dev')
  await playerPage.fill('input[placeholder="senha"]', 'Test1234!')
  await playerPage.getByRole('button', { name: 'Entrar com Email' }).click()
  await playerPage.goto(sessionUrl)
  await expect(playerPage.getByRole('button', { name: 'Deletar' })).toHaveCount(0)
  await playerContext.close()
})
