import { test, expect } from '@playwright/test'

async function loginMaster(page: any) {
  await page.goto('/login')
  await page.evaluate(() => { localStorage.clear(); sessionStorage.clear() })
  await page.fill('input[placeholder="email"]', 'master.teste@pbta.dev')
  await page.fill('input[placeholder="senha"]', 'Test1234!')
  await page.getByRole('button', { name: 'Entrar com Email' }).click()
}

test('Rolagem com modificadores soma atributo+movimento corretamente', async ({ page }) => {
  await loginMaster(page)
  await page.getByPlaceholder('Nome').fill('Campanha Mods')
  await page.getByPlaceholder('Plot (opcional)').fill('Mods')
  await page.getByRole('button', { name: 'Criar' }).click()
  const campaignsJson = await page.evaluate(() => localStorage.getItem('pbta_campaigns'))
  const campaigns = JSON.parse(campaignsJson || '{}')
  const campaignId = Object.keys(campaigns)[Object.keys(campaigns).length - 1]
  await page.goto(`/campaigns/${campaignId}/moves`)
  await page.getByLabel('Nome').fill('Ataque Forte')
  await page.getByLabel('Descrição').fill('Ataque')
  await page.getByLabel('Modificador').selectOption('2')
  await page.getByRole('button', { name: 'Criar' }).click()
  await page.goto(`/characters/${campaignId}`)
  await page.getByText('Minha Ficha').waitFor()
  await page.getByLabel('Nome').fill('Jogador Mods')
  await page.getByLabel('Antecedentes').fill('Teste')
  await page.getByRole('group', { name: 'Força' }).getByLabel('1', { exact: true }).click()
  await page.getByRole('group', { name: 'Agilidade' }).getByLabel('1', { exact: true }).click()
  await page.getByRole('group', { name: 'Sabedoria' }).getByLabel('1', { exact: true }).click()
  await page.getByText('Ataque Forte').click()
  await page.getByRole('button', { name: 'Criar Ficha' }).click()
  await page.goto(`/campaigns/${campaignId}/sessions`)
  await page.getByLabel('Nome').fill('Sessão Mods')
  const d = new Date()
  const ds = `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`
  await page.getByLabel('Data').fill(ds)
  await page.getByRole('button', { name: 'Criar' }).click()
  await page.getByRole('link', { name: 'Abrir' }).click()
  await page.getByLabel('Quem').selectOption({ label: 'Jogador: Jogador Mods' })
  await page.getByLabel('Atributo').selectOption({ label: 'forca' })
  await page.getByLabel('Movimento').selectOption({ label: 'Ataque Forte' })
  await page.getByRole('button', { name: 'Rolar' }).click()
  const totalText = await page.getByText(/Total:/).textContent()
  const parts = totalText?.match(/Total: (\d+) \+ (\-?\d+) = (\d+) → (\w+)/)
  const baseSum = Number(parts?.[1] || '0')
  const mod = Number(parts?.[2] || '0')
  const total = Number(parts?.[3] || '0')
  expect(total).toBe(baseSum + mod)
  expect(mod).toBeGreaterThanOrEqual(2)
})